### ISSUE TITLE
opencv2/highgui/highgui.hpp' file not found

### ISSUE THREAD

**Issue by olivero86** [iMicknl/cordova-plugin-openalpr#12] opened 2017-02-15 22:02 UTC
When I run ionic build ios I get the following error message:

```
/Plugins/cordova-plugin-openalpr/PlateScanner.h:12:10: fatal error: 'opencv2/highgui/highgui.hpp' file not found                 
#include "opencv2/highgui/highgui.hpp"  
```
Thanks

**Comment by iMicknl** [comment] 2017-02-16 17:26
Can you provide us with some more details? Please open the project in xCode and try to compile and run it. This can be an issue with the code signing / project settings in xCode.
(cc @m3lv1n)

**Comment by olivero86** [comment] 2017-02-17 08:33
I fixed some project settings but still cannot run it. Below is the error I now get in XCode 8.2.1.
When I run the ionic build, I get the following error:
`** BUILD FAILED **                                                                                         
                                                                                                                                                                                        
The following build commands failed:                                                                       
                                                                                                           
        CompileC build/openalpr1.build/Debug-iphonesimulator/openalpr1.build/Objects-normal/i386/OpenALPR.o
i386 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler                                             
(1 failure)                                                                                                
                                                                                                           
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/oli/Sites/Demo/openalpr1/platforms
,ARCHS=i386,-target,openalpr1,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATIO
d/emulator,SHARED_PRECOMPS_DIR=/Users/oli/Sites/Demo/openalpr1/platforms/ios/build/sharedpch    `
And when I try to run the generated project I get this error in Xcode:
<img width="950" alt="bildschirmfoto 2017-02-17 um 09 28 43" src="https://cloud.githubusercontent.com/assets/10154639/23058134/bd4fc0ca-f4f3-11e6-969b-6f5bd56a310d.png">

**Comment by m3lv1n** [comment] 2017-02-21 21:46
Hi @olivero86,

Ive managed to reproduce your error. For some reason the opencv framework is not added correctly to the project. We do not know yet if this is because of a directory structure error or a configuration error.

In the meantime you can bypass this error by moving the contents of the opencv2.framework/versions/A folder up to the opencv2.framework/ folder is (like the image below) afterwards it is safe to delete the now empty versions folder.

<img width="415" alt="screen shot 2017-02-21 at 22 35 44" src="https://cloud.githubusercontent.com/assets/10958064/23186116/32f08f04-f886-11e6-8558-ee7f0da127b8.png">

Now build the project again.

We do not know yet when we will release a final fix since we are both busy graduating at the moment.

Kind regards, Melvin

**Comment by iMicknl** [comment] 2018-03-17 16:02
(added as known issue to the readme, closing issue)

**Closed by iMicknl** 2018-03-17 16:02 UTC
Labels: bug

**Comment by tomevs88** [comment] 2018-04-19 06:41
Any updates on this being fixed? I am currently running our own build for openAlpr but would like to use a recomended plugin. Thanks

**Comment by iMicknl** [comment] 2018-04-19 15:11
Please have a look at the [README](https://github.com/iMicknl/cordova-plugin-openalpr#opencv2highguihighguihpp-file-not-found-when-compiling-ios-app). This is still a known issue which isn't related to our plugin, but to Cordova. We provide a work-around in the readme.
